default:
  data_dir: "data"
  db_path: "data/interim/local.duckdb"
  sample_frac: 1.0
  data:
    manifest: "metadata/data_manifest.csv"
    species_requests: "metadata/species_requests.csv"
    occurrence:
      min_year: 2000
      min_lat: null
      state_province: "Tasmania"
      boundary: null
      boundary_simplify: 1000
      fields:
        - decimalLatitude
        - decimalLongitude
        - eventDate
        - vernacularName
        - scientificName
        - dataResourceName
        - taxonConceptID
      map:
        basemap: "rnaturalearth"
        show_title: false
        show_legend: false
        point_colour: "#2171b5"
        point_size: 1.6
        additional_points:
          path: "data/raw/lyr_pt.csv"
          colour: "#d73027"
          size: null
        tile_provider: "Esri.WorldImagery"
        tile_zoom: 8
        tile_outline_colour: "#ffffff"
        tile_graticule: true
        topo_output_path: "outputs/maps/species_topo.png"
        bounding_box:
          top_left:
            lat: -40.2
            lon: 144.0
          length_km: 400
        output_path: "outputs/maps/species_occurrences.png"

  ala:
    email: "barry.brook@utas.edu.au"
    atlas: "ALA"
    caching: true
    verbose: false
    download_reason_id: 4

local:
  inherits: default

ci:
  inherits: default
  sample_frac: 0.02

slurm:
  inherits: default
  workers: 64
  time: "06:00:00"
  mem_gb: 4
