default:
  data_dir: "data"
  db_path: "data/interim/local.duckdb"
  sample_frac: 1.0
  data:
    manifest: "metadata/data_manifest.csv"
    species_requests: "metadata/species_requests.csv"
    occurrence:
      min_year: 2000
      min_lat: null
      state_province: "Tasmania"
      boundary: null
      boundary_simplify: 1000
      fields:
        - decimalLatitude
        - decimalLongitude
        - eventDate
        - vernacularName
        - scientificName
        - dataResourceName
        - taxonConceptID
      map:
        basemap: "rnaturalearth"
        show_title: false
        show_legend: false
        point_colour: "#2171b5"
        point_size: 1.6
        additional_points:
          path: "data/raw/lyr_pt.csv"
          colour: "#d73027"
          size: null
        tile_provider: "Esri.WorldImagery"
        tile_zoom: 8
        tile_outline_colour: "#ffffff"
        tile_graticule: true
        topo_output_path: "outputs/maps/species_topo.png"
        bounding_box:
          top_left:
            lat: -40.2
            lon: 144.0
          length_km: 400
        output_path: "outputs/maps/species_occurrences.png"
    camera_sites:
      path: "data/raw/lyr_op.csv"
      central_site: "wc_s10_c5"
      bbox_half_km: 20
      basemap:
        provider: "list_tasveg"
        type: "wms"
        url: "https://services.thelist.tas.gov.au/arcgis/services/Public/NaturalEnvironment/MapServer/WMSServer"
        version: "1.3.0"
        layers:
          - "TASVEG_4.0_Groups55513"
        crs: "EPSG:3857"        # safe for WMS 1.3.0 (no axis flip)
        styles: "default"
        format: "image/png"
        max_scale: 100000
        transparent: true
        width: 2048
        height: 2048
        dpi: 96
        legend_path: "outputs/tiles/tasveg_camera_sites_legend.png"
        output_path: "outputs/tiles/tasveg_camera_sites.png"
      map:
        output_path: "outputs/maps/camera_sites.png"
        scale_bar_location: "tl"
        north_arrow_location: "tr"
        point_size_min: 1.0
        point_size_max: 5.0
        zero_obs_colour: "#050505"
        positive_obs_colour: "#d73027"

  ala:
    email: "barry.brook@utas.edu.au"
    atlas: "ALA"
    caching: true
    verbose: false
    download_reason_id: 4

local:
  inherits: default

ci:
  inherits: default
  sample_frac: 0.02

slurm:
  inherits: default
  workers: 64
  time: "06:00:00"
  mem_gb: 4
